### ISSUE TITLE
Собрать информацию о сетях фаст-фуда, зарегистрированных в Украине

### ISSUE THREAD

**Issue by crimaniak** [Vercabra/FoDeCo#2]

**Comment by crimaniak** [comment]
для затравки:  [раз](https://biz.censor.net/resonance/3089610/komu_prinadlejat_fastfudy_v_ukraine#:~:text=%D0%92%20%D0%BD%D0%B0%D1%88%20%D1%80%D0%B5%D0%B9%D1%82%D0%B8%D0%BD%D0%B3%20%D0%B2%D0%BE%D1%88%D0%BB%D0%B8%20%D1%81%D0%B5%D1%82%D0%B8,10%20%D1%82%D0%BE%D1%87%D0%B5%D0%BA%20%D0%B2%20%D0%B3%D0%BE%D1%80%D0%BE%D0%B4%D0%B0%D1%85%20%D0%A3%D0%BA%D1%80%D0%B0%D0%B8%D0%BD%D1%8B.&text=%D0%A1%D1%80%D0%B5%D0%B4%D0%B8%20%D0%BD%D0%B8%D1%85%20Fast%20Food%20Systems,%D0%94%D0%B2%D0%B0%20%D0%93%D1%83%D1%81%D1%8F%22%2C%20The%20Varenik.), [два](https://www.pizzatravel.com.ua/rus/Ukraina/3/setevie_restorani_bistrogo_pitaniya_v_ukraine).

**Comment by Vercabra** [comment]
> для затравки: [раз](https://biz.censor.net/resonance/3089610/komu_prinadlejat_fastfudy_v_ukraine#:~:text=%D0%92%20%D0%BD%D0%B0%D1%88%20%D1%80%D0%B5%D0%B9%D1%82%D0%B8%D0%BD%D0%B3%20%D0%B2%D0%BE%D1%88%D0%BB%D0%B8%20%D1%81%D0%B5%D1%82%D0%B8,10%20%D1%82%D0%BE%D1%87%D0%B5%D0%BA%20%D0%B2%20%D0%B3%D0%BE%D1%80%D0%BE%D0%B4%D0%B0%D1%85%20%D0%A3%D0%BA%D1%80%D0%B0%D0%B8%D0%BD%D1%8B.&text=%D0%A1%D1%80%D0%B5%D0%B4%D0%B8%20%D0%BD%D0%B8%D1%85%20Fast%20Food%20Systems,%D0%94%D0%B2%D0%B0%20%D0%93%D1%83%D1%81%D1%8F%22%2C%20The%20Varenik.), [два](https://www.pizzatravel.com.ua/rus/Ukraina/3/setevie_restorani_bistrogo_pitaniya_v_ukraine).

Был на этих сайтах. Думаю возьму только эти сети. То-есть список. Для начала. Что-бы понимать от чего отталкиватся.

**Comment by Vercabra** [comment]
Look list of restourants
